# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id_album', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id_grupo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fk_grupo_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rSocial.genero')),
            ],
        ),
        migrations.CreateModel(
            name='miembro',
            fields=[
                ('id_miembro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fk_miembro_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rSocial.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id_post', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
                ('id_grupo_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rSocial.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='fk_album_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rSocial.grupo'),
        ),
    ]
