# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rSocial', '0004_auto_20160419_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='inSesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
